# pyproject.toml
[project]
name = "comfyui-prompt-magic"
description = "ComfyUI prompt enhance nodes and string utilities"
version = "0.0.1"
license = { text = "MIT" }
dependencies  = []

[project.urls]
Repository = "https://github.com/ArtemKo7v/ComfyUI-Prompt-Magic"

[tool.comfy]
PublisherId = "artemko7v"
DisplayName = "ComfyUI Prompt Enhance Nodes"
